Repository UofT-Group7-Project-1/Group7_Project-1, pull requests merged in 2020-11, with the labels that each got.

#2 first commit
  README.md
Labels: documentation

#4 file structure and file links
  README.md
  assets/css/style.css
  assets/javascript/script.js
  index.html
Labels: documentation

#7 Readme
  README.md
Labels: documentation

#11 html5 boilerplate
  .gitignore
  LICENSE
  assets/css/normalize.css
  assets/css/style.css
  assets/images/Project1_Homepage.png
  assets/images/Project1_Results_Page.png
  assets/images/favicon.ico
  humans.txt
  index.html
Labels: enhancement

#12 Garcia millares
  assets/images/Project1_Results_Page.png
  humans.txt
  user_story.md
Labels: documentation

#19 Kava
  assets/javascript/script.js
  humans.txt
  index.html
Labels: enhancement

#21 Garcia millares
  .DS_Store
  NYT_userStory.md
  assets/images/NYT_filmReviewSearch_homepage.png
  assets/images/NYT_filmReviewSearch_resultsPage.png
  humans.txt
Labels: documentation

#25 New wireframe images
  assets/.DS_Store
  assets/images/New Wireframe 1 results.png
  assets/images/New Wireframe homepage.png
  index.html
Labels: documentation

#31 Placeholder logo and minor html/css changes
  assets/css/style.css
  assets/images/Placeholder_Logo.png
  index.html
Labels: enhancement

#37 Garcia millares
  README.md
  assets/images/.DS_Store
  assets/images/New Wireframe 1 results.png
  assets/images/New Wireframe results.png
  assets/images/Project1_Homepage.png
  assets/images/Project1_Results_Page.png
Labels: documentation

#45 created carousel
  assets/css/style.css
  assets/javascript/script.js
  index.html
Labels: enhancement

#46 Minor html changes and revised logo
  assets/css/style.css
  assets/images/Project Logo.png
  index.html
Labels: enhancement

#48 added search results div
  assets/javascript/script.js
  index.html
Labels: enhancement

#50 created divs for column 2
  assets/css/style.css
  index.html
Labels: enhancement

#55 removed minor errors
  assets/css/style.css
  assets/javascript/script.js
  index.html
Labels: bug

#72 Fixed broken wireframe image links in README
  README.md
  assets/javascript/script.js
  index.html
Labels: documentation

#78 Kava
  assets/css/style.css
  assets/javascript/script.js
  index.html
Labels: enhancement

#80 small clean up
  assets/javascript/script.js
  index.html
Labels: documentation

#82 created footer
  assets/css/style.css
  assets/images/Tmdb_logo.jpg
  assets/images/ny.png
  assets/images/nyt.png
  assets/images/play.jpeg
  assets/images/tmdb.png
  assets/images/twitterICON.jpeg
  assets/javascript/script.js
  humans.txt
  index.html
Labels: enhancement

#83 added trailer to else statement
  assets/css/style.css
  assets/javascript/script.js
  index.html
Labels: enhancement

#90 Minor documentation update
  README.md
  assets/images/Working_Project_Sample.png
Labels: documentation
